const assert = require('node:assert/strict');
const { boot } = require('./harness.cjs');
const page=boot();const run=page.run;
assert.equal(run('state.tasks.map(t=>t.score).join()'),'100,90,90,90,90');
assert.equal(run('calculateScore({contact:"abcdefgh",format:"abcdefgh"}).score'),10);
assert.equal(run('calculateScore({contact:"   ",format:"abcdefgh"}).score'),0);
page.inputs.find(e=>e.dataset.field==='title').value='Ручной черновик';
page.elements['draft-contact'].value='user@example.com';
run('saveDraft();saveDraft()');
assert.equal(run('state.tasks.length'),6);
const restored=boot(page.storage.value);
assert.equal(restored.inputs.find(e=>e.dataset.field==='title').value,'Ручной черновик');
page.elements['confirm-check'].checked=false;run('publish()');assert.equal(run('getTask().published'),undefined);
page.elements['confirm-check'].checked=true;run('publish()');assert.equal(run('getTask().published'),true);
run('saveDraft()');assert.equal(run('getTask().published'),true);
page.elements['catalog-search'].value='  medLINE  ';run('renderCatalog()');assert.ok(page.elements['catalog-list'].innerHTML.includes('MedLine'));assert.ok(!page.elements['catalog-list'].innerHTML.includes('SmallMart'));
page.elements['catalog-search'].value='zzzz';run('renderCatalog()');assert.ok(page.elements['catalog-list'].innerHTML.includes('не найдено'));
assert.equal(run('safeLink("javascript:alert(1)")'),'');
assert.equal(run('validateAnalysis("broken",["data"],[{field:"data",text:"Какие данные?"}]).fallback'),true);
assert.equal(run('validateAnalysis({missingFields:[],questions:[],suggestions:[]},[],[]).fallback'),false);
page.elements['draft-text'].value='Хотим улучшить запись в клинику';page.elements['simulate-ai-error'].checked=true;run('aiAnalyze()');assert.ok(page.elements['ai-result'].innerHTML.includes('fallback'));
run('openOffer("task1")');page.elements['offer-team'].value='team1';page.elements['offer-idea'].value='Создадим удобный экран записи для пациентов';page.elements['offer-plan'].value='За четыре часа подготовим форму и проверим сценарий';
page.elements['offer-link'].value='javascript:alert(1)';run('submitOffer()');assert.equal(run('state.tasks.find(t=>t.id==="task1").offers.length'),1);
page.elements['offer-link'].value='https://example.com';run('submitOffer();submitOffer()');assert.equal(run('state.tasks.find(t=>t.id==="task1").offers.length'),2);
run('decideOffer("task1","p1","accepted");decideOffer("task1",state.tasks.find(t=>t.id==="task1").offers[1].id,"accepted")');assert.equal(run('state.tasks.find(t=>t.id==="task1").offers.filter(o=>o.status==="accepted").length'),2);
assert.equal(boot(page.storage.value).run('state.tasks.find(t=>t.id==="task1").offers[0].status'),'accepted');
assert.equal(boot('{bad').run('state.tasks.length'),5);assert.equal(boot('{}').run('state.tasks.length'),5);
const blocked=boot(null,true);blocked.run('saveDraft()');assert.ok(blocked.elements.toast.textContent.includes('Не удалось сохранить'));
page.elements['catalog-search'].value='';page.elements['catalog-level'].value='draft';run('renderCatalog()');assert.ok(!page.elements['catalog-list'].innerHTML.includes('MedLine Clinic'));
page.elements['catalog-level'].value='all';page.elements['catalog-sort'].value='rating';run('renderCatalog()');assert.ok(page.elements['catalog-list'].innerHTML.indexOf('100/100')<page.elements['catalog-list'].innerHTML.indexOf('90/100'));
const stale=JSON.parse(page.storage.value);stale.tasks.forEach(t=>t.score=999);assert.equal(boot(JSON.stringify(stale)).run('state.tasks.find(t=>t.id==="task1").score'),100);
assert.equal(run('validateAnalysis({missingFields:[],questions:"wrong",suggestions:[]},[],[]).fallback'),true);
run('currentRole="student";decideOffer("task2","p2","accepted")');assert.equal(run('state.tasks.find(t=>t.id==="task2").offers[0].status'),'pending');
console.log('PASS: scoring, manual save/reload, publication, search, fallback, URL safety, offers, team selection, storage errors');
