const assert = require('node:assert/strict');
const { boot } = require('./harness.cjs');
const flush = async () => { for (let i = 0; i < 5; i++) await new Promise(setImmediate); };

async function main() {
  const page = boot(), run = page.run;
  page.inputs.find(e => e.dataset.field === 'title').value = 'Ручной черновик';
  page.elements['draft-contact'].value = 'old@example.com';
  page.elements['draft-contact'].emit('input');
  run('saveDraft()');
  page.elements['draft-contact'].value = 'new@example.com';
  page.elements['draft-contact'].emit('input');
  run('saveDraft()');
  assert.equal(boot(page.storage.value).elements['draft-contact'].value, 'new@example.com');
  page.elements['draft-contact'].value = '';
  run('saveDraft()');
  assert.equal(boot(page.storage.value).elements['draft-contact'].value, '');
  page.elements['confirm-check'].checked = true;
  run('publish()'); assert.equal(run('getTask().published'), undefined);
  page.elements['draft-contact'].value = 'user@example.com';
  run('publish()'); assert.equal(run('getTask().published'), true);
  assert.equal(run('getTask().score'), 0, 'Low score must not block publication');
  page.elements['catalog-industry'].value = 'Ритейл';
  run('renderCatalog()');
  assert.ok(page.elements['catalog-list'].innerHTML.includes('SmallMart'));
  assert.ok(!page.elements['catalog-list'].innerHTML.includes('MedLine'));
  page.elements['catalog-level'].value = 'draft';
  run('renderCatalog()'); assert.ok(page.elements['catalog-list'].innerHTML.includes('не найдено'));
  assert.equal(run('validateAnalysis({missingFields:["data","users"],questions:[{field:"data",text:"A"},{field:"data",text:"B"}],suggestions:[]},["data","users"],[{},{}]).fallback'), true);
  run('loadDemo();aiAnalyze()');
  assert.ok((page.elements['ai-result'].innerHTML.match(/question-item/g) || []).length >= 3);
  const answer = page.elements['ai-result'].answers.find(el => el.dataset.questionField === 'data');
  answer.value = 'Тестовое расписание и примеры записей';
  answer.emit('input');
  assert.equal(page.inputs.find(el => el.dataset.field === 'data').value, answer.value);
  assert.equal(run('readCardFields().score'), 40, 'Answer updates card and rating immediately');

  run('decideOffer("task1","p1","accepted");openProgress("task1","p1")');
  page.elements['progress-stage'].value = 'Прототип';
  page.elements['progress-note'].value = 'Бизнес проверил прототип выбора свободного времени';
  page.elements['progress-status'].value = 'in_progress';
  run('saveProgress()'); assert.equal(run('teamPoints("team2")'), 0);
  page.elements['progress-status'].value = 'done';
  run('saveProgress()'); assert.equal(run('teamPoints("team2")'), 0);
  page.elements['progress-confirm'].checked = true;
  run('saveProgress();saveProgress()');
  assert.equal(run('teamPoints("team2")'), 20, 'No duplicate reward');
  page.elements['progress-stage'].value = 'Тестирование';
  run('currentRole="student";saveProgress()');
  assert.equal(run('teamPoints("team2")'), 20);
  run('currentRole="business";saveProgress()');
  assert.equal(run('teamPoints("team2")'), 40);
  assert.equal(boot(page.storage.value).run('teamPoints("team2")'), 40);
  run('renderData()'); assert.ok(page.elements['teams-data'].innerHTML.includes('<td>40</td>'));
  const blocked = boot(undefined, true);
  blocked.run('decideOffer("task1","p1","accepted")');
  assert.equal(blocked.run('state.tasks[0].offers[0].status'), 'pending');
  blocked.run('state.tasks[0].offers[0].status="accepted";openProgress("task1","p1")');
  blocked.elements['progress-stage'].value = 'Прототип';
  blocked.elements['progress-note'].value = 'Готовый прототип записи';
  blocked.elements['progress-status'].value = 'done';
  blocked.elements['progress-confirm'].checked = true;
  blocked.run('saveProgress()'); assert.equal(blocked.run('teamPoints("team2")'), 0);

  const output = { title: 'Подзадача', goal: 'Цель', input_data: 'Данные', expected_artifact: 'Прототип', acceptance_criteria: 'Проверка', constraints: 'Ограничения' };
  let resolve, calls = 0;
  const ai = boot(undefined, false, () => { calls++; return new Promise(r => { resolve = r; }); });
  ai.run('openDependentAgent("task1")');
  ai.elements['dependent-focus'].value = 'Исследовать запись';
  ai.elements['dependent-role'].value = 'Исследователь';
  ai.dependentInputs[0].value = 'Старый ответ';
  ai.run('generateDependentAgent();generateDependentAgent();saveDependentTask()');
  assert.equal(calls, 1);
  assert.equal(ai.dependentInputs[0].value, '');
  assert.equal(ai.elements['save-dependent-btn'].disabled, true);
  assert.equal(ai.run('state.dependentTasks.length'), 0);
  resolve({ ok: true, status: 200, json: async () => output }); await flush();
  assert.equal(ai.elements['save-dependent-btn'].disabled, false);
  ai.run('saveDependentTask()');
  assert.equal(ai.run('state.dependentTasks[0].source'), 'llm-api');
  ai.run('openDependentAgent("task1");generateDependentAgent()');
  ai.elements['dependent-modal-close'].emit('click');
  ai.run('openDependentAgent("task2")');
  resolve({ ok: true, status: 200, json: async () => output }); await flush();
  assert.equal(ai.dependentInputs[0].value, '', 'Late response must not populate another task');
  let failures = 0;
  const fallback = boot(undefined, false, async () => { failures++; return { ok: false, status: 502, json: async () => ({ error: 'unavailable' }) }; });
  fallback.run('openDependentAgent("task1")');
  fallback.elements['dependent-role'].value = 'Исследователь';
  fallback.run('generateDependentAgent()'); await flush();
  assert.equal(failures, 1, 'Model errors must not trigger duplicate requests');
  assert.equal(fallback.run('dependentSource'), 'local-fallback');
  assert.ok(fallback.elements['dependent-agent-result'].note.innerHTML.includes('fallback'));
  console.log('PASS: edited/cleared contact, combined filters, confirmed points, no double awards, persistence rollback, LLM loading, stale responses, fallback without duplicate calls');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
